name: "Session 2 Homework Pipeline"

on:
  push:
    branches:
      - "production"
    paths:
      - "app/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        default: dev
        options:
          - dev
          - staging
          - production
      reason:
        description: "Reason for deployment (optional)"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Reason: ${{ github.event.inputs.reason }}"